name: Build and Release APK

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Authenticate with Expo
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Build APK with EAS
        run: npx eas-cli build --platform android --non-interactive --profile production

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Build URL
        run: |
          BUILD_URL=$(npx eas-cli build:list --json | jq -r '.[0].artifacts.buildUrl')
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV

      - name: Download APK
        run: curl -o app-release.apk "$BUILD_URL"

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app-release.apk

      - name: Notify Build URL
        run: echo "✅ Build complete! Download APK: $BUILD_URL"
