on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Configure npm global path
        run: |
          npm config set prefix ~/.npm-global
          echo "export PATH=\"$HOME/.npm-global/bin:$PATH\"" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli --unsafe-perm=true

      - name: Verify EAS CLI installation
        run: eas --version

      - name: Authenticate with EAS
        run: eas login --token ${{ secrets.EAS_ACCESS_TOKEN }}

      - name: Build Android AAB
        run: npx eas build -p android --profile production --clear-cache
