name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Release aab for playstore 
        run: eas build --platform android
